seisbench/seisbench

- .github/workflows/test_push.yml
- requirements.txt
- requirements/req_common.txt
- requirements/req_dependent.txt
- seisbench/models/base.py
- setup.py
Summarising the changes in this PR:
- Add custom install dependencies for windows (GDAL lib)
- Install via differing requirements files depending on the OS detected
- Expands the CI tests to include both windows and mac OS systems in the tests
One note to consider for the future is that, whilst the combined installation logic may work at the moment, future dependency conflicts arising due to differing OSs or the versions of the python packages themselves may result in errors when using this combined approach. If this happens, we can change the cartopy, fiona, etc. plotting libs to optional 'soft' dependencies.
> Windows CI

- .github/workflows/main_push.yml
- .github/workflows/pull_request.yml
- README.md
- requirements.txt
- seisbench/models/base.py
- setup.py
- tests/test_models.py
This commit implements streaming processing for WaveformModels. This has several advantages:
- Enables parallelization between and within each step
- Allows batching across multiple stations, thereby improving GPU utilization
- Reduces memory consumption for point prediction models in case of long traces
As this only modifies the backend, but does not introduce any changes in the user interface, I'd suggest to publish it as 0.1.8 (instead of 0.2.0), even though it's technically not a bugfix. What do you think @jawooll ? In addition, because it's a somewhat more complicated change, I'd ask you to have a look at it.
Closes #40
> Implement streaming annotations

- seisbench/generate/__init__.py
- seisbench/generate/labeling.py
- tests/test_generate.py
Hi @yetinam ,
Triangular labels have been used to train Earthquake Transformer in [Mousavi et al., 2020](https://www.nature.com/articles/s41467-020-17591-w), while Seisbench does not implement it yet. 
Here I built the TriangularLabeller which is similar to the ProbabilisticLabeller class. It's a pretty small commit, and hopefully will be useful for future users.
> Implement triangular labeler

- seisbench/data/base.py
This PR suppresses the pandas warning for mixed dtypes when loading the metadata from csv. It occurs primarily because we allow empty metadata fields. However, the warning can be pretty annoying, in particular, when loading datasets with many chunks because each chunk will trigger a warning. At the same time, we cannot pass a dictionary with dtypes to `read_csv` due to the flexible names of metadata columns. I think suppressing the warning should be fine here.
@jawooll : Just running this by you to see if you agree on hiding the warning.
> Suppress warning for mixed dtypes when loading metadata

- seisbench/data/base.py
- seisbench/generate/generator.py
- tests/test_data.py
- tests/test_generate.py
This PR extends the function `WaveformDataset.get_idx_from_trace_name` and the `SteerableGenerator` to accept the chunk and dataset as secondary keys. This is necessary because the trace name can be (and in many cases will be) non-unique.
For details see also #78. (Closes #78)
> Resolve trace name collisions for chunked datasets and MultiWaveformDatasets

- seisbench/models/base.py
- tests/test_models.py
Currently prediction time-series from overlapping windows are combined into one prediction time-series spanning the entire stream fed to the model. To combine these overlapping windows the average of these windows is taken. For EQTransformer combining by taking the mean is not ideal as the prediction value depends quite strongly on when the phase occurs within the 60s window used for prediction. 
Consider the below case for the same earthquake recorded on site SNZO (and reported in the [EQTransformer paper](https://www.nature.com/articles/s41467-020-17591-w/figures/4):
```python
from obspy import UTCDateTime
from obspy.clients.fdsn import Client
import numpy as np
import seisbench.models as sbm
import matplotlib.pyplot as plt
def plot_predictions(tr, cft, p_time):
colors = {"Detection": …
```
> Add max-stack option to reassemble array predictions

- seisbench/models/base.py
- tests/test_models.py
See #90 for details
Technically, this is a change in behaviour and should therefore be in a new minor version instead of a new patch version. However, I'd suggest to just stick to the liberal interpretation of versioning we are currently using, given that we are still at major version 0, i.e., early development.
> Changed severity of mismatching traces in annotate from Exception to Warning (Closes #90)

- seisbench/models/base.py
This is a simple speed-up enhancement that speeds-up nan-trimming by about 4x on my machine. Trimming nan's at the start and end of predictions was one of the slower parts of the model workflow (taking about 0.15s for a day of 100 Hz data) - while this isn't that slow, this method runs in ~0.04s for the same data).
> Speedup nan trim

- docs/_ext/optional_argument_helper.py
- docs/conf.py
- seisbench/models/aepicker.py
- seisbench/models/base.py
- seisbench/models/cred.py
- seisbench/models/eqtransformer.py
- seisbench/models/gpd.py
- seisbench/models/phasenet.py
- tests/test_models.py
This PR cleans up the optional arguments for `annotate/classify` and their documentation. It contains three contributions:
- A Sphinx extension to automatically document all optional arguments.
- A parameter validation for the optional arguments. Any unknown argument passed to `annotate/classify` will raise a warning.
- Default values for all parameters are now defined centrally in the `_annotate_args` dictionary instead as scattered throughout the code.
Closes #100
> Documentation and validation for optional arguments for annotate/classify

- seisbench/data/base.py
- seisbench/generate/__init__.py
- seisbench/generate/augmentation.py
- seisbench/generate/generator.py
- seisbench/generate/windows.py
- tests/test_data.py
- tests/test_generate.py
This PR adds data grouping. This includes:
- grouping in WaveformDataset and MultiWaveformDataset
- a new GroupGenerator
- adjustment of several augmentations to deal with grouped data
Grouping allows to automatically retrieve sets of metadata and waveforms from a dataset. The waveforms are selected based on a common key. For example, this enables to group the data by event and then train multi-station models. However, as any grouping is possible, there are countless options for using the scheme.
This PR does not contain any models. It also does not contain any grouping for the `annotate`/`classify` function. Due to the scale of this feature addition, and to keep the PRs somewhat reasonably sized, I think it's still worthwhile including this part already.
> Add data grouping

- seisbench/data/base.py
- tests/test_data.py
This PR implements several performance optimization for accessing datasets. They improve throughput and thereby training speed considerably. The specific improvements are:
- cache output of `_chunks_with_path_cache`. The return value is static and the function is called for every call to `get_waveforms`. Reduces runtime of `get_waveforms` by ~20 %.
- Add option to activate a metadata lookup table. Reduces runtime for `get_sample` by more than 50 %. As this comes at the cost of a longer compute at initialisation and significantly higher memory overhead, this optimization is deactivated by default.
- *(only for grouped datasets)* remove unnecessary copy operations in the list of groups (for large datasets speedup can exceed 10x)
*Remark:* Due to a lack of potential reviewers, I'll merge the …
> Performance optimization for dataset access

- seisbench/models/aepicker.py
- seisbench/models/base.py
- seisbench/models/cred.py
- seisbench/models/deepdenoiser.py
- seisbench/models/eqtransformer.py
- seisbench/models/gpd.py
- seisbench/models/phasenet.py
- tests/test_models.py
- Make `strict` and `flexible_horizontal_components` annotate arguments instead of listing them separately in the function head.
- Remove `default_args` set in the constructor by overwrites to `_annotate_args`. This ensures that the documentation lists the correct default values.
- Factor out function to query arguments with defaults from the `_annotate_args`.
> Homogenized annotate arguments

- examples/03a_training_phasenet.ipynb
In the [`03a_training_phasenet.ipynb`](https://github.com/seisbench/seisbench/blob/main/examples/03a_training_phasenet.ipynb) notebook the `model.eval()` call was missing (code-block 11). This call is needed to close the re-trained model, and is done automatically by the `annotate` method. In the notebook, though, must be specified. I've added such a switch in the `test_loop` function as well.
> bug_fix: adding model.eval() and model.train() in example notebooks

- seisbench/models/base.py
- tests/test_models.py
Instead of separating instruments with different channel codes into different groups, they are now put into the same group, e.g., BH? and HH? are now in the same group. The grouping key is NET.STA.LOC. This change is necessary for many OBS deployment, where the channel codes aren't identical between the hydrophone and the seismic sensor.
> Change grouping behaviour for grouping="instrument" (Closes #196)

- .pre-commit-config.yaml
- seisbench/generate/augmentation.py
- seisbench/generate/labeling.py
- tests/test_generate.py
1. Create an bool-type variable "noise_column" in the PickLabeller class to determine whether a noise label will be constructed. If the noise_column is false, no noise label will be created, and labels will not be normalized.
2. Update the `SupervisedLabeller::_check_labels()` function
3. Update `test_probabilistic_pick_labeller()`
```python
from seisbench.generate import ProbabilisticLabeller
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)
p=50
s=100
state_dict = {
"X": (
10 * np.random.rand(3, 200),
{
"trace_p_arrival_sample": p,
"trace_s_arrival_sample": s,
},
)
}
fig,axs=plt.subplots(4,2,sharex="all")
for i,noise_column in enumerate([True,False]):
labeller = ProbabilisticLabeller(
dim=0, shape="gaussian",sigma=20, noise_column=noise_column
)
labeller(state_dict) …
```
> Adding options for disabling normalization and noise label for ProbabilisticLabeller, and checking picks for AddGap and ChannelDropout.

- .pre-commit-config.yaml
- seisbench/generate/augmentation.py
- tests/test_generate.py
In pull request https://github.com/seisbench/seisbench/pull/222, only the metadata is changed if there is any pick in a gap.
It may be helpful to add an option to change labels directly. For example. when one waveform is staked on another (e.g. [benchmark/augmentations.py](https://github.com/seisbench/pick-benchmark/blob/main/benchmark/augmentations.py)) to generate a new trace, the metadata is kept unchanged and only the label is changed. In this case, adding the gap to the labels directly is a better choice.
- I added two label_keys `label_keys` and `noise_id` to `AddGap` and `ChannelDropout`
- Two new tests: `test_channel_dropout_with_picks_in_gap` and `test_add_gap_to_waveform_and_labels`
I forgot to pull your commit at the beginning, so I manually resolved the conflicts. I hope it …
> Add an option for AddGap and ChannelDropout to modify label directly

- seisbench/models/base.py
Adding argument copy: `annotate(st, copy=False)`
Safes me 0.5 seconds per call.
> base: stream copy now optional.

- .github/workflows/main_push.yml
- .github/workflows/publish-to-pypi.yml
- Add Python 3.12 to CI
- Switch publishing workflow to Python 3.12 to avoid future deprecation issues
> Python 3.12 (Closes #263)

- seisbench/generate/labeling.py
- tests/test_generate.py
Hi Jannes,
when using the original PhaseNet model or diting as base models for transfer learning, the label IDs are wrong. Default labels_ids are {"P": 0, "S": 1, "Noise": 2}, however, PhaseNet and diting have {"Noise": 0, "P": 1, "S": 2}. Therefore, transfer learning was not possible since the ids did not depend on the given labels by the loaded model. I rewrote the method "_colums_to_dict_and_labels" and added an argument model_labels to get the correct dictionary and label IDs.
Cheers,
Janis
> Bugfix for PhaseNet label IDs

- contrib/benchmark_model_annotate.py
- docs/pages/documentation/util.rst
- seisbench/data/base.py
- seisbench/models/aepicker.py
- seisbench/models/base.py
- seisbench/models/cred.py
- seisbench/models/deepdenoiser.py
- seisbench/models/eqtransformer.py
- seisbench/models/gpd.py
- seisbench/models/phasenet.py
- seisbench/models/team.py
- seisbench/util/__init__.py
- seisbench/util/arraytools.py
- tests/models/test_annotate_compatibility.py
- tests/test_data.py
- tests/test_models.py
- tests/test_util.py
Pre- and postprocessing in the annotate function was so far done per window and in numpy. This PR changes the processing to a batched mode running on PyTorch. This also ensures that all processing can happen on the GPU if available. In addition, this now allows to wrap the three processing steps in a thread, allowing to release the GIL during the heavy numeric operations. Overall, this will reduce run times, in particular, on GPU.
As this change improves the efficiency of the asyncio implementation, it removes the (suboptimal) process implementation completely.
To ensure compatibility with the previous implementation, a suite of tests has been added and the former `annotate_window_pre`/`annotate_window_post` functions are retained. These functions and tests should be removed in a future …
> Change annotate logic from windowed to batched pre- and postprocessing

- pyproject.toml
Caused by obspy dependency problem (https://github.com/obspy/obspy/issues/3484). Will be fixed in obspy v1.5. The version pinning should be removed then.
> Pin numpy version to avoid CI crashes

- docs/pages/benchmark_datasets.rst
- docs/pages/data_format.rst
This PR contains just two typo fixes in the documentation.
> DOC: Fix two typos 

- seisbench/models/base.py
- seisbench/models/phasenet.py
- tests/test_models.py
Add the option to increase the number of filters used in PhaseNet by a constant factor. This option has been proposed by Naoi et al. (2024), see https://doi.org/10.1186/s40623-024-02091-8. The `jma_wc` weight is already available in the SeisBench repository, but sets a version requirement to the future 0.9 release as it relies on this PR. The regular JMA weights are already usable though.
> Add PhaseNetWC model through filter_factor option

- .github/workflows/main_push.yml
- pyproject.toml
- follows Python version support schedule (https://devguide.python.org/versions/)
- for debugging purpose, adds outputs of the 10 slowest tests from each run
- removes obsolete dependency on `pytest-asyncio`
- removes version pinning `numpy<2` because obspy is now compatible with numpy 2
> Add Python 3.13 to the test matrix

- seisbench/models/base.py
- seisbench/models/phasenet.py
- tests/test_models.py
Also cleans up the overlap specification for VariableLengthPhaseNet
> Enable specifying overlaps in annotate as fractions instead (Closes #353)

- seisbench/models/base.py
- tests/test_models.py
Enables models to automatically select their input (and output) length based on the input, e.g., use longer input windows for long streams.
PR also contains some additional clean-ups for the `annotate` logic.
> Enable models with dynamic input and output length

- docs/pages/data_format.rst
Just a few typo fixes in the documentation page "The SeisBench data format". No code changes.
> DOC: Fix a few typos in documentation page "The SeisBench data format"

- seisbench/models/seisdae.py
When applying the Denoiser on a stream, each trace had the same label. This is fixed with this PR.
> [bugfix] Labelling for denoised channels was not set
